version: "3"
services:
  app:
    command: "/bin/bash -c '\
      python -m pip install Django; \
      exec tail -f /dev/null'"
    image: "python"
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    working_dir: "/app"
